#!/bin/sh
#
# Example upload hook for filebin2.
#
# This script is called during file upload, after the file has been received
# from the client but before it is stored in S3. It can be used to validate
# or inspect uploaded files, for example using an anti virus scanner.
#
# Arguments:
#   $1 - Bin ID
#   $2 - Filename
#   $3 - Content type (MIME type)
#   $4 - File size in bytes
#   $5 - Path to the temporary file
#
# Exit codes:
#   0 - Accept the upload
#   1 - Reject the upload (403 Forbidden)
#   Any other - Reject the upload (500 Internal Server Error)
#
# The last line of stdout is returned to the client as the response message
# when the upload is rejected.
#
# Usage:
#   filebin2 --upload-exec-hook /path/to/this/script
#

BIN="$1"
FILENAME="$2"
CONTENT_TYPE="$3"
FILE_SIZE="$4"
FILE_PATH="$5"

# Example: reject files larger than 100 MB
#MAX_SIZE=104857600
#if [ "$FILE_SIZE" -gt "$MAX_SIZE" ]; then
#    echo "File exceeds the maximum allowed size of 100 MB"
#    exit 1
#fi

# Example: reject certain content types
#case "$CONTENT_TYPE" in
#    application/x-executable*|application/x-sharedlib*)
#        echo "Executable files are not allowed"
#        exit 1
#        ;;
#esac

# Example: reject files with certain extensions
#case "$FILENAME" in
#    *.exe|*.bat|*.cmd|*.com|*.scr)
#        echo "This file type is not allowed"
#        exit 1
#        ;;
#esac

# Example: scan the file with ClamAV
#RESULT=$(clamdscan --no-summary "$FILE_PATH" 2>&1)
#if [ $? -ne 0 ]; then
#    echo "$RESULT"
#    exit 1
#fi

# Accept the upload
exit 0
