#!/bin/bash
#
# Helper script to run tests:
# - Test results formatted as XML to be compatible with CircleCI.
# - Coverage reports as html for easy overview.
#

#set -euxo pipefail
set -uxo pipefail
#go test -failfast -cover -v -race -mod=vendor -coverprofile=coverage.out -p 1 ./... | tee tests.out
go test -cover -v -race -mod=vendor -coverprofile=coverage.out -p 1 ./... | tee tests.out
ret=$?
mkdir -p tests
cat tests.out | go-junit-report > tests/tests.xml
go tool cover -html=coverage.out -o artifacts/coverage.html
go tool cover -func=coverage.out
exit $ret
