 CREATE TABLE bin (
	id		VARCHAR(64) NOT NULL PRIMARY KEY,
	updated		TIMESTAMP NOT NULL,
	created		TIMESTAMP NOT NULL,
	downloads	BIGINT NOT NULL
);

CREATE TABLE file (
	id		SERIAL NOT NULL PRIMARY KEY,
	bin_id		VARCHAR(64) REFERENCES bin(id) ON DELETE CASCADE,
	filename	VARCHAR(128) NOT NULL,
	mime		VARCHAR(128) NOT NULL,
	bytes		BIGINT NOT NULL,
	checksum	VARCHAR(128) NOT NULL,
	downloads	BIGINT NOT NULL,
	nonce		VARCHAR(128) NOT NULL,
	updated		TIMESTAMP NOT NULL,
	created		TIMESTAMP NOT NULL,
	UNIQUE(bin_id, filename)
);
