 CREATE TABLE bin (
	id		SERIAL NOT NULL PRIMARY KEY,
	bid		VARCHAR(64) NOT NULL,
	updated		TIMESTAMP NOT NULL,
	created		TIMESTAMP NOT NULL,
	UNIQUE(bid)
);

CREATE TABLE file (
	id		SERIAL NOT NULL PRIMARY KEY,
	bin_id		INTEGER REFERENCES bin(id) ON DELETE CASCADE,
	filename	VARCHAR(128) NOT NULL,
	size		INT NOT NULL,
	checksum	VARCHAR(128) NOT NULL,
	updated		TIMESTAMP NOT NULL,
	created		TIMESTAMP NOT NULL,
	UNIQUE(bin_id, filename)
);
